INSERT INTO ACCOUNT_TEST VALUES (1,'이름','1234','DBMS@NAVER.COM',CURRENT_TIMESTAMP,NULL);
INSERT INTO ACCOUNT_TEST VALUES (2,'이름2','12344','DB1MS@NAVER.COM',CURRENT_TIMESTAMP,NULL);

INSERT INTO table_test VALUES ('a2');
INSERT INTO table_test VALUES ('a4');

COMMIT;