INSERT INTO visits (ID_VISIT, NAME_VISIT) VALUES ('JS3322', 'JS');
INSERT INTO visits (ID_VISIT, NAME_VISIT) VALUES ('JS3000', 'JS');
INSERT INTO visits (ID_VISIT, NAME_VISIT) VALUES ('JS3001', 'JS');