version: "3"
services:
  node:
    image: node:14
    working_dir: /usr/src/app
    environment:
      # - NODE_ENV=development
      - DB_USER=postgres
      - DB_PW=password
      - DB_TYPE=postgres
      - DB_HOST=postgresql
    volumes:
      - ./src:/usr/src/app
    ports:
      - 3000:3000
    command: bash -c "npm install && npm start"