version: "3"

services:
  redis6379:
      container_name: redis6379
      image: redis:latest
      restart: always
      container_name: redis
      hostname: redis6379
      network_mode: host
      ports:
          - 6379:6379
      volumes:
          - /data:/data
          - /conf/redis.conf:/usr/local/etc/redis/redis.conf
          - /acl/users.acl:/etc/redis/users.acl
      command: redis-server /usr/local/etc/redis/redis.conf